### ISSUE TITLE
karpenter on-demand:spot 비율 조절

### ISSUE THREAD

**Issue by choisungwook** [choisungwook/portfolio#143]
# 개요
* pod의 nodeAffinity설정으로, karpenter가 생성하는 노드 on-demand,spot 비율을 조절

```yaml
topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: capacity-spread
        whenUnsatisfiable: DoNotSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: capacity-spread
          operator: In
          values:
          - "on-demand-1"
          - "on-demand-2"
          - "spot-1"
          - "spot-2"
          - "spot-3"
```

# on-demand,spot 설정 시 주의사항
1. consolidation 효율이 떨어진다.
* on-demand, spot을 분리했기 때문에 각 노드에 대해서만 consolidation이 설정됨
2. pod replica 개수가 적으면 서비스 장애 확률이 증가
* consoliation, drift로 on-demand 노드가 교체될 때, spot 노드가 죽으면 서비스 장애 발생
* pod replica개수가 많을 수록 노드 개수가 많아지므로 안전성이 증가

# 참고자료
- https://medium.com/deutsche-telekom-gurgaon/karpenter-magic-deployments-splitting-spot-on-demand-2e0edf1df8de
